<div class="topleft">
<h1><a href="/"><img src="/SFFDB.png" alt="SFFDB - The Science Fiction and Fantasy Database" class="logo" /></a></h1>
</div>
<div class="register topright">
{% if user %}
<a href="/account/">My Account</a> | <a href="/logout/">Logout</a>
{% else %}
<a href="/register/">Register</a> | <a href="/login/">Login</a>
{% endif %}
</div>
<div class="top">
<form action="http://www.google.com/cse" id="cse-search-box">
  <div>
    <input type="hidden" name="cx" value="partner-pub-9036937779788337:9029724212" />
    <input type="hidden" name="ie" value="UTF-8" />
    <input type="text" name="q" size="42" />
    <input type="submit" name="sa" value="Search" />
  </div>
</form>
<script type="text/javascript" src="http://www.google.com/jsapi"></script>
<script type="text/javascript" src="http://www.google.com/cse/t13n?form=cse-search-box&amp;t13n_langs=en"></script>
<script type="text/javascript" src="http://www.google.com/cse/brand?form=cse-search-box&amp;lang=en"></script>
</div>
